name: Metrics
on:
  schedule:
    - cron: "22 3 * * *"   # daily at 03:22 UTC
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: connect2abdulaziz
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Karachi
          plugin_followup: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_ignored: html, css, jupyter notebook
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_lines: yes
          plugin_repositories: yes
          plugin_topics: yes
          plugin_topics_limit: 12
      - name: Save SVG to repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git init
          git remote add origin https://github.com/${GITHUB_REPOSITORY}.git
          git fetch --depth=1 origin
          git checkout -B main || git checkout -B master || true
          echo "Generated on $(date -u)" > .metrics_timestamp
          mv metrics.svg metrics.svg || true
          git add metrics.svg .metrics_timestamp
          git commit -m "chore(metrics): update metrics.svg"
          git push origin HEAD
