name: Metrics
on:
  schedule:
    - cron: "22 3 * * *"    # daily
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - README.md
      - .github/workflows/metrics.yml

permissions:
  contents: write   # allow committing metrics.svg

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate & commit metrics.svg
        uses: lowlighter/metrics@latest
        with:
          # PAT for reading your activity (public_repo or repo if you want private stats)
          token: ${{ secrets.METRICS_TOKEN }}

          # This lets the action commit the file to your repo (no manual git needed)
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: main
          filename: metrics.svg

          user: connect2abdulaziz
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Karachi

          # plugins (tweak as you like)
          plugin_followup: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_ignored: html, css, jupyter notebook
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_lines: yes
          plugin_repositories: yes
          plugin_topics: yes
          plugin_topics_limit: 12
