name: Metrics
on:
  schedule:
    - cron: "0 6 * * *"    # daily at 6 AM UTC
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - README.md
      - .github/workflows/metrics.yml

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Generate metrics (light theme)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: main
          filename: metrics-light.svg
          user: connect2abdulaziz
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Karachi
          config_display: large
          config_padding: 6, 12
          # Light theme colors
          config_base_color: "#ffffff"
          config_text_color: "#24292f"
          config_title_color: "#0969da"
          config_icon_color: "#656d76"
          # Only essential stats - no extra plugins
          
      - name: Generate metrics (dark theme)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: main
          filename: metrics-dark.svg
          user: connect2abdulaziz
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Karachi
          config_display: large
          config_padding: 6, 12
          # Dark theme colors matching your current theme
          config_base_color: "#0d1117"
          config_text_color: "#e6edf3"
          config_title_color: "#4158d0"
          config_icon_color: "#7d8590"
          # Only essential stats - no extra plugins
